language: python
sudo: required
dist: xenial
python: "3.7"

install:
  - pip install cwltool

# We need to cd into tests in order for coverage to work
# (it searches for .coverage in the cwd)
script:
  - cwltool --validate broad-best-practice-data-pre-processing-workflow-4-1-0-0_decomposed.cwl
